//HintName: global__DuplicateProperties_DF9371DA.g.cs
// <auto-generated />

#nullable enable
#pragma warning disable CS1591

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("SlusserLabs.AssemblyInfo", "1.0.0")]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
public partial class DuplicateProperties
{
    public const global::System.String Description = "Assembly description";
    public const global::System.String Description = "Metadata description";
}
