//HintName: global__Example_ThisAssembly_8A128306.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS1591

namespace Example;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("SlusserLabs.AssemblyInfo", "1.0.0")]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
public static partial class ThisAssembly
{
    public const global::System.String Configuration = "Release";
    public const global::System.String Company = "SlusserLabs";
    public const global::System.String AssemblyTitle = "AssemblyInfo Tests";
    public const global::System.String Description = "Snapshot tests";
    public const global::System.String Product = "AssemblyInfo";
    public const global::System.String Copyright = "SlusserLabs, Jacob Slusser";
    public const global::System.String AssemblyVersion = "1.2.3.4";
    public const global::System.String InformationalVersion = "1.2.3+abcdef";
    public const global::System.String FileVersion = "1.2.3.4";
    public const global::System.String BuildDate = "2026-08-17";
    public const global::System.String Repository_Url = "https://example.test/repository";
}
