//HintName: global__MetadataOnly_FFE29349.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS1591

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("SlusserLabs.AssemblyInfo", "1.0.0")]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
public partial class MetadataOnly
{
    public const global::System.String BuildDate = "2026-08-17";
    public const global::System.String Commit = "abcdef";
}
