//HintName: global__AssemblyAttributesOnly_DEEA1839.g.cs
// <auto-generated />

#nullable enable
#pragma warning disable CS1591

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("SlusserLabs.AssemblyInfo", "1.0.0")]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
public partial class AssemblyAttributesOnly
{
    public const global::System.String Company = "SlusserLabs";
    public const global::System.String AssemblyTitle = "AssemblyInfo Tests";
    public const global::System.String Description = "";
    public const global::System.String AssemblyVersion = "1.2.3.4";
}
