//HintName: global__UnknownOptions_F43E304E.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS1591

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("SlusserLabs.AssemblyInfo", "1.0.0")]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
public partial class UnknownOptions
{
}
