using System.CodeDom.Compiler;
using System.Globalization;
using System.IO;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace SlusserLabs.AssemblyInfo;

internal static class EmbeddedSources
{
    private const string _header = """
        // <auto-generated/>
        #nullable enable
        #pragma warning disable CS1591


        """;
    private const string _generatedCodeAttributes = """
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SlusserLabs.AssemblyInfo", "1.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
        """;

    internal static string[] StandardMemberNames { get; } =
    [
        "Configuration",
        "Company",
        "AssemblyTitle",
        "Description",
        "Product",
        "Copyright",
        "AssemblyVersion",
        "InformationalVersion",
        "FileVersion",
    ];

    internal static string Generate(AssemblyInfoTarget target, AssemblyInfoData assemblyInfo)
    {
        var source = new StringBuilder(_header);
        using var stringWriter = new StringWriter(source, CultureInfo.InvariantCulture);
        using var writer = new IndentedTextWriter(stringWriter, "    ");

        if (target.NamespaceName is not null)
        {
            writer.Write("namespace ");
            writer.Write(target.NamespaceName);
            writer.WriteLine(";");
            writer.WriteLine();
        }

        for (var index = 0; index < target.TypeDeclarations.Count; index++)
        {
            if (index == target.TypeDeclarations.Count - 1)
            {
                WriteLines(writer, _generatedCodeAttributes);
            }

            writer.WriteLine(target.TypeDeclarations[index]);
            writer.WriteLine("{");
            writer.Indent++;
        }

        AppendConstant(writer, target.Options, AssemblyInfoOptions.AssemblyConfiguration, "Configuration", assemblyInfo.Configuration);
        AppendConstant(writer, target.Options, AssemblyInfoOptions.AssemblyCompany, "Company", assemblyInfo.Company);
        AppendConstant(writer, target.Options, AssemblyInfoOptions.AssemblyTitle, "AssemblyTitle", assemblyInfo.Title);
        AppendConstant(writer, target.Options, AssemblyInfoOptions.AssemblyDescription, "Description", assemblyInfo.Description);
        AppendConstant(writer, target.Options, AssemblyInfoOptions.AssemblyProduct, "Product", assemblyInfo.Product);
        AppendConstant(writer, target.Options, AssemblyInfoOptions.AssemblyCopyright, "Copyright", assemblyInfo.Copyright);
        AppendConstant(writer, target.Options, AssemblyInfoOptions.AssemblyVersion, "AssemblyVersion", assemblyInfo.Version);
        AppendConstant(
            writer,
            target.Options,
            AssemblyInfoOptions.AssemblyInformationalVersion,
            "InformationalVersion",
            assemblyInfo.InformationalVersion);
        AppendConstant(writer, target.Options, AssemblyInfoOptions.AssemblyFileVersion, "FileVersion", assemblyInfo.FileVersion);
        AppendMetadata(writer, target.Options, assemblyInfo.Metadata);

        for (var index = target.TypeDeclarations.Count - 1; index >= 0; index--)
        {
            writer.Indent--;
            writer.WriteLine("}");
        }

        writer.Flush();

        return source.ToString();
    }

    internal static string CreateIdentifier(string key)
    {
        // Assembly metadata keys are arbitrary strings, so unsupported characters become underscores
        var identifier = new StringBuilder(key.Length + 1);

        for (var index = 0; index < key.Length; index++)
        {
            var character = key[index];
            identifier.Append(SyntaxFacts.IsIdentifierPartCharacter(character) ? character : '_');
        }

        if (identifier.Length == 0)
        {
            identifier.Append('_');
        }
        else if (!SyntaxFacts.IsIdentifierStartCharacter(identifier[0]))
        {
            identifier.Insert(0, '_');
        }

        var result = identifier.ToString();

        return SyntaxFacts.GetKeywordKind(result) == SyntaxKind.None ? result : "@" + result;
    }

    private static void AppendConstant(
        IndentedTextWriter writer,
        AssemblyInfoOptions options,
        AssemblyInfoOptions option,
        string name,
        string? value)
    {
        if ((options & option) == 0)
        {
            return;
        }

        writer.Write("public const global::System.String? ");
        writer.Write(name);
        writer.Write(" = ");
        writer.Write(value is null ? "null" : SymbolDisplay.FormatLiteral(value, quote: true));
        writer.WriteLine(";");
    }

    private static void AppendMetadata(IndentedTextWriter writer, AssemblyInfoOptions options, EquatableArray<AssemblyMetadataEntry> metadata)
    {
        if ((options & AssemblyInfoOptions.AssemblyMetadata) == 0)
        {
            return;
        }

        for (var index = 0; index < metadata.Count; index++)
        {
            var entry = metadata[index];
            writer.Write("public const global::System.String ");
            writer.Write(CreateIdentifier(entry.Key));
            writer.Write(" = ");
            writer.Write(SymbolDisplay.FormatLiteral(entry.Value, quote: true));
            writer.WriteLine(";");
        }
    }

    private static void WriteLines(IndentedTextWriter writer, string value)
    {
        var lines = value.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries);

        foreach (var line in lines)
        {
            writer.WriteLine(line);
        }
    }
}
