using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;
using SlusserLabs.AssemblyInfo.Infrastructure;

namespace SlusserLabs.AssemblyInfo;

internal static class EmbeddedSources
{
    private const string _header = """
        // <auto-generated />

        #nullable enable
        #pragma warning disable CS1591


        """;

    private const string _generatedCodeAttributes = """
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SlusserLabs.AssemblyInfo", "1.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
        """;

    public static string[] StandardMemberNames { get; } =
    [
        "Configuration",
        "Company",
        "AssemblyTitle",
        "Description",
        "Product",
        "Copyright",
        "AssemblyVersion",
        "InformationalVersion",
        "FileVersion",
    ];

    public static string Generate(AssemblyInfoTarget target, AssemblyInfoData assemblyInfo)
    {
        var source = new StringBuilder(_header);
        using var stringWriter = new StringWriter(source, CultureInfo.InvariantCulture);
        using var writer = new IndentedTextWriter(stringWriter, "    ");

        if (target.NamespaceName is not null)
        {
            writer.WriteLine($"namespace {target.NamespaceName};");
            writer.WriteLine();
        }

        for (var index = 0; index < target.TypeDeclarations.Count; index++)
        {
            if (index == target.TypeDeclarations.Count - 1)
            {
                WriteLines(writer, _generatedCodeAttributes);
            }

            writer.WriteLine(target.TypeDeclarations[index]);
            writer.WriteLine("{");
            writer.Indent++;
        }

        AppendConstant(writer, target.Options, GenerateAssemblyInfoOptions.AssemblyConfiguration, "Configuration", assemblyInfo.Configuration);
        AppendConstant(writer, target.Options, GenerateAssemblyInfoOptions.AssemblyCompany, "Company", assemblyInfo.Company);
        AppendConstant(writer, target.Options, GenerateAssemblyInfoOptions.AssemblyTitle, "AssemblyTitle", assemblyInfo.Title);
        AppendConstant(writer, target.Options, GenerateAssemblyInfoOptions.AssemblyDescription, "Description", assemblyInfo.Description);
        AppendConstant(writer, target.Options, GenerateAssemblyInfoOptions.AssemblyProduct, "Product", assemblyInfo.Product);
        AppendConstant(writer, target.Options, GenerateAssemblyInfoOptions.AssemblyCopyright, "Copyright", assemblyInfo.Copyright);
        AppendConstant(writer, target.Options, GenerateAssemblyInfoOptions.AssemblyVersion, "AssemblyVersion", assemblyInfo.Version);
        AppendConstant(writer, target.Options, GenerateAssemblyInfoOptions.AssemblyInformationalVersion, "InformationalVersion", assemblyInfo.InformationalVersion);
        AppendConstant(writer, target.Options, GenerateAssemblyInfoOptions.AssemblyFileVersion, "FileVersion", assemblyInfo.FileVersion);

        AppendMetadata(writer, target.Options, assemblyInfo.Metadata);

        for (var index = target.TypeDeclarations.Count - 1; index >= 0; index--)
        {
            writer.Indent--;
            writer.WriteLine("}");
        }

        writer.Flush();
        return source.ToString();
    }

    public static string CreateIdentifier(string key)
    {
        // Assembly metadata keys are arbitrary strings, so unsupported characters become underscores
        var identifier = new StringBuilder(key.Length + 1);

        for (var index = 0; index < key.Length; index++)
        {
            var character = key[index];
            identifier.Append(SyntaxFacts.IsIdentifierPartCharacter(character) ? character : '_');
        }

        if (identifier.Length == 0)
        {
            identifier.Append('_');
        }
        else if (!SyntaxFacts.IsIdentifierStartCharacter(identifier[0]))
        {
            identifier.Insert(0, '_');
        }

        var result = identifier.ToString();

        return SyntaxFacts.GetKeywordKind(result) == SyntaxKind.None ? result : "@" + result;
    }

    private static void AppendConstant(IndentedTextWriter writer, GenerateAssemblyInfoOptions options, GenerateAssemblyInfoOptions option, string name, string? value)
    {
        if ((options & option) == 0 || value is null)
        {
            return;
        }

        var literal = SymbolDisplay.FormatLiteral(value, quote: true);
        writer.WriteLine($"public const global::System.String {name} = {literal};");
    }

    private static void AppendMetadata(IndentedTextWriter writer, GenerateAssemblyInfoOptions options, EquatableArray<StringPair> metadata)
    {
        if ((options & GenerateAssemblyInfoOptions.AssemblyMetadata) == 0)
        {
            return;
        }

        for (var index = 0; index < metadata.Count; index++)
        {
            var entry = metadata[index];
            var name = CreateIdentifier(entry.Key);
            var literal = SymbolDisplay.FormatLiteral(entry.Value, quote: true);
            writer.WriteLine($"public const global::System.String {name} = {literal};");
        }
    }

    private static void WriteLines(IndentedTextWriter writer, string value)
    {
        var lines = value.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries);
        foreach (var line in lines)
        {
            writer.WriteLine(line);
        }
    }
}
